# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [sfn, source, zipper-1, zipper-2]

  zipper-1:
    desc: run zipper-1
    dir: zipper-1
    cmds:
      - "go run zipper_1.go"

  zipper-2:
    desc: run zipper-2
    dir: zipper-2
    cmds:
      - "go run zipper_2.go"

  zipper-3:
    desc: run zipper-3
    dir: zipper-3
    cmds:
      - "go run zipper_3.go"

  sfn-1:
    desc: sfn-1
    deps: [sfn-1-build]
    cmds:
      - "./bin/sfn-1{{exeExt}}"

  sfn-2:
    desc: sfn-2
    deps: [sfn-2-build]
    cmds:
      - "./bin/sfn-2{{exeExt}}"

  sfn-3:
    desc: sfn-3
    deps: [sfn-3-build]
    cmds:
      - "./bin/sfn-3{{exeExt}}"

  source-1:
    desc: source-1
    # deps: [source-1-build]
    dir: source-1
    cmds:
      # - "./bin/source{{exeExt}}"
      - "go run source.go"

  source-2:
    desc: source-2
    # deps: [source-2-build]
    dir: source-2
    cmds:
      - "go run source.go"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./bin"

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/source.go"

  sfn-1-build:
    desc: build sfn-1
    cmds:
      - "go build -o ./bin/sfn-1{{exeExt}} sfn-1/sfn_echo.go"

  sfn-2-build:
    desc: build sfn-2
    cmds:
      - "go build -o ./bin/sfn-2{{exeExt}} sfn-2/sfn_echo.go"

  sfn-3-build:
    desc: build sfn-3
    cmds:
      - "go build -o ./bin/sfn-3{{exeExt}} sfn-3/sfn_echo.go"
